MovieBooker-backend/MovieBooker/Pages/Users/Cart/PayTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Org.BouncyCastle.Crypto.Prng;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http.Headers;
using System.Security.Cryptography.Xml;
using System.Text;

namespace MovieBooker.Pages.Users.Cart
{
    public class PayTicketModel : PageModel
    {
        private readonly IAuthenService _authenticationService;
        public PayTicketModel(IAuthenService authenticationService)
        {
            _authenticationService = authenticationService;
        }
        public List<ScheduleDTO> schedules { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }
        public List<SeatDTO> seats { get; set; }
        public List<UserDTO> Users { get; set; }

        public async Task<IActionResult> OnPostBuyTicketAsync(int timeSlotId, double movieprice, List<int> seatId,
            int movieId, int scheduleId, double finalTotalPrice)
        {
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = await
           _httpClient.GetAsync($"https://localhost:5000/api/Schedule/GetSchedule?$filter=schedulesId eq {scheduleId}");
            if (response.IsSuccessStatusCode)
            {
                schedules = await response.Content.ReadFromJsonAsync<List<ScheduleDTO>>();
            }
            HttpResponseMessage response2 = await _httpClient.GetAsync($"https://localhost:5000/api/Seat/GetSeat");
            if (response2.IsSuccessStatusCode)
            {
                var allSeats = await response2.Content.ReadFromJsonAsync<List<SeatDTO>>();
                seats = allSeats.Where(seat => seatId.Contains(seat.SeatId)).ToList();
            }
            TempData["totalprice"] = finalTotalPrice;
            TempData["seatId"] = JsonConvert.SerializeObject(seatId);
            return Page();
        }

        //public async Task<IActionResult> OnPostPaymentAsync(int timeslotid, int movieid, double totalprice, DateTime resdate)
        //{
        //    var seatIdJson = TempData["seatId"].ToString();
        //    List<int> seatId = JsonConvert.DeserializeObject<List<int>>(seatIdJson);
        //    var accessToken = await _authenticationService.GetAccessTokenAsync();
        //    HttpClient _httpClient = new HttpClient();
        //    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        //    var handler = new JwtSecurityTokenHandler();
        //    var jwtToken = handler.ReadToken(accessToken) as JwtSecurityToken;
        //    var email = jwtToken.Claims.FirstOrDefault(claim => claim.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress")?.Value;
        //    HttpResponseMessage response = await _httpClient.GetAsync($"https://localhost:5000/api/User/GetAllUser?$filter=email eq '{email}'");
        //    if (response.IsSuccessStatusCode)
        //    {
        //        Users = await response.Content.ReadFromJsonAsync<List<UserDTO>>();
        //    }
        //    int userId = 0;
        //    foreach (var id in Users)
        //    {
        //        userId = id.UserId;
        //    }

        //    for (int i = 0; i < seatId.Count(); i++)
        //    {
        //        var res = new CreateResevationDTO
        //        {
        //            MovieId = movieid,
        //            UserId = userId,
        //            TimeSlotId = timeslotid,
        //            SeatId = seatId[i],
        //            ReservationDate = resdate,
        //            Status = false,
        //            TotalAmount = totalprice / seatId.Count(),
        //        };
        //        HttpResponseMessage response2 = await
        //       _httpClient.PostAsJsonAsync("https://localhost:5000/api/Reservation/CreateReservation", res);
        //    }
        //    return RedirectToPage("/Users/Cart/BookedSuccess");
        //}

        public async Task<IActionResult> OnPostPaymentAsync(int timeslotid, int movieid,
            double totalprice, DateTime resdate, int schedulesId, string confirmemail, string payment)
        {
            HttpClient httpClient = new HttpClient();
            var seatIdJson = TempData["seatId"].ToString();
            List<int> seatId = JsonConvert.DeserializeObject<List<int>>(seatIdJson);
            var accessToken = await _authenticationService.GetAccessTokenAsync();
            HttpClient _httpClient = new HttpClient();
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            var handler = new JwtSecurityTokenHandler();
            var jwtToken = handler.ReadToken(accessToken) as JwtSecurityToken;
            var email = jwtToken.Claims.FirstOrDefault(claim => claim.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress")?.Value;
            HttpResponseMessage response2 = await _httpClient.GetAsync($"https://localhost:5000/api/User/GetAllUser?$filter=email eq '{email}'");
            if (response2.IsSuccessStatusCode)
            {
                Users = await response2.Content.ReadFromJsonAsync<List<UserDTO>>();
            }
            int userId = 0;
            foreach (var id in Users)
            {
                userId = id.UserId;
            }

            if (payment == "vnpay")
            {
                var model = new VnPaymentRequestModel
                {
                    Amount = totalprice,
                    CreatedDate = DateTime.Now,
                    FullName = confirmemail,
                    Description = "movie ticket",
                    OrderId = new Random().Next(1000, 9999)
                };

                HttpResponseMessage response = await httpClient.PostAsJsonAsync("https://localhost:5000/api/VnPay/CreatePaymentUrl", model);
                if (response.IsSuccessStatusCode)
                {
                    string paymentUrlJson = await response.Content.ReadAsStringAsync();
                    var paymentUrlObject = JsonConvert.DeserializeObject<Dictionary<string, string>>(paymentUrlJson);
                    if (paymentUrlObject != null && paymentUrlObject.TryGetValue("paymentUrl", out string paymentUrl))
                    {
                        var reservations = new List<CreateResevationDTO>();
                        for (int i = 0; i < seatId.Count(); i++)
                        {
                            var res = new CreateResevationDTO
                            {
                                MovieId = movieid,
                                UserId = userId,
                                TimeSlotId = timeslotid,
                                SeatId = seatId[i],
                                ReservationDate = resdate,
                                Status = true,
                                TotalAmount = totalprice / seatId.Count(),
                            };
                            reservations.Add(res);
                        }
                        TempData["resevation"] = JsonConvert.SerializeObject(reservations);
                        TempData["seatId"] = JsonConvert.SerializeObject(seatId);
                        TempData["email"] = email;
                        TempData["scheduleId"] = schedulesId;
                        TempData["confirmemail"] = confirmemail;
                        return Redirect(paymentUrl);
                    }
                }
                return RedirectToPage("/Error");
            }
            else if (payment == "paypal")
            {
                var response = await _httpClient.PostAsync("https://localhost:5000/api/PayPal/create-payment", new StringContent(totalprice.ToString(), Encoding.UTF8, "application/json"));
                if (response.IsSuccessStatusCode)
                {
                    var responseBody = await response.Content.ReadAsStringAsync();
                    var approvalUrl = JObject.Parse(responseBody)["approvalUrl"].ToString();

                    var reservations = new List<CreateResevationDTO>();
                    for (int i = 0; i < seatId.Count(); i++)
                    {
                        var res = new CreateResevationDTO
                        {
                            MovieId = movieid,
                            UserId = userId,
                            TimeSlotId = timeslotid,
                            SeatId = seatId[i],
                            ReservationDate = resdate,
                            Status = true,
                            TotalAmount = totalprice / seatId.Count(),
                        };
                        reservations.Add(res);
                    }
                    TempData["resevation"] = JsonConvert.SerializeObject(reservations);
                    TempData["seatId"] = JsonConvert.SerializeObject(seatId);
                    TempData["email"] = email;
                    TempData["scheduleId"] = schedulesId;
                    TempData["confirmemail"] = confirmemail;
                    return Redirect(approvalUrl);
                }
                return RedirectToPage("/Error");
            }
            return RedirectToPage("/Error");
        }
    }
}

MovieBooker-backend/MovieBooker/Pages/Users/Cart/Seats.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.DTO;
using MovieBooker.Models;

namespace MovieBooker.Pages.Users.Cart
{
    public class BookSeatModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public TicketDTO ticket {  get; set; }
        public List<ScheduleDTO> schedules { get; set; }
        public List<SeatDTO> seats { get; set; }    
        public List<ReservationDTO> reservations { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            string? date = ticket.start;
            int? movieId = ticket.movieId;
            int? theartr = ticket.theartr;
            int? slot = ticket.timeslot;
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response2 = await
            _httpClient.GetAsync($"https://localhost:5000/api/Schedule/GetSchedule?$filter=scheduleDate eq {date} and movieId eq {movieId} and timeSlotId eq {slot} and theaterId eq {theartr}");
            if (response2.IsSuccessStatusCode)
            {
                schedules = await response2.Content.ReadFromJsonAsync<List<ScheduleDTO>>();
            }
            int roomId = (int)schedules.First().RoomId;
            HttpResponseMessage response3 = await _httpClient.GetAsync($"https://localhost:5000/api/Seat/GetSeat?$filter=theatersId eq {theartr} and roomId eq {roomId}");
            if (response3.IsSuccessStatusCode)
            {
                seats = await response3.Content.ReadFromJsonAsync<List<SeatDTO>>();
            }
            HttpResponseMessage response4 = await _httpClient.GetAsync($"https://localhost:5000/api/Reservation?$filter=reservationDate eq {date} and movieId eq {movieId} and timeSlotId eq {slot} ");
            if (response4.IsSuccessStatusCode)
            {
                reservations = await response4.Content.ReadFromJsonAsync<List<ReservationDTO>>();
            }
            var bookedSeats = new HashSet<int>(reservations.Select(r => r.SeatId.GetValueOrDefault()));
            foreach (var seat in seats)
            {
                seat.IsBooked = bookedSeats.Contains(seat.SeatId);
            }

            return Page();  
        }
    }
}

MovieBooker-backend/MovieBooker/Pages/Users/Cart/Ticket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Models;
using System.Net.Http;

namespace MovieBooker.Pages.Users.Cart
{
    public class TicketModel : PageModel
    {
        [BindProperty]
        public int? SelectedTheaterId { get; set; }

        [BindProperty]
        public int? SelectedTimeSlotId { get; set; }
        public List<DateTime> SelectedDates { get; set; }
        public List<TheaterDTO> theaters { get; set; }

        public List<ScheduleDTO> schedules { get; set; }
        private readonly IAuthenService _authenticationService;
        public TicketModel(IAuthenService authenticationService)
        {
            _authenticationService = authenticationService;
        }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            var accessToken = await _authenticationService.GetAccessTokenAsync();
            if (accessToken == null)
            {
                return RedirectToPage("/Login");
            }
            else
            {

                DateTime startDate = DateTime.Today;
                DateTime endDate = DateTime.Today.AddDays(28);

                string start;
                if (Request.Cookies.TryGetValue("selectedDate", out var selectedDate))
                {
                    start = selectedDate;
                }
                else
                {
                    start = startDate.ToString("yyyy-MM-dd");
                }

                //string end = endDate.ToString("yyyy-MM-dd");
                SelectedDates = InitializeDefaults(startDate, endDate);
                HttpClient _httpClient = new HttpClient();
                HttpResponseMessage response = await _httpClient.GetAsync("https://localhost:5000/api/Theater/GetAllTheater");
                if (response.IsSuccessStatusCode)
                {
                    theaters = await response.Content.ReadFromJsonAsync<List<TheaterDTO>>();
                }
                if (schedules == null)
                {
                    HttpResponseMessage response2 = await _httpClient.GetAsync($"https://localhost:5000/api/Schedule/GetSchedule?$filter=scheduleDate eq {start} and movieId eq {id}");
                    if (response2.IsSuccessStatusCode)
                    {
                        schedules = await response2.Content.ReadFromJsonAsync<List<ScheduleDTO>>();
                    }
                }
                TempData["movieId"] = id;
                return Page();
            }
        }
        private List<DateTime> InitializeDefaults(DateTime startDate, DateTime endDate)
        {
            List<DateTime> datesInRange = new List<DateTime>();
            for (DateTime date = startDate; date <= endDate; date = date.AddDays(1))
            {
                datesInRange.Add(date);
            }
            return datesInRange;
        }

        public async Task<IActionResult> OnGetScheduleAsync(DateTime selectedate, int movieId)
        {

            string date = selectedate.ToString("yyyy-MM-dd");
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response2 = await _httpClient.GetAsync($"https://localhost:5000/api/Schedule/GetSchedule?$filter=scheduleDate eq {date} and movieId eq {movieId}");
            if (response2.IsSuccessStatusCode)
            {
                schedules = await response2.Content.ReadFromJsonAsync<List<ScheduleDTO>>();
            }

            return await OnGetAsync(movieId);
        }

        public async Task<IActionResult> OnPostAsync(int movieId)
        {
            string? start = null;
            if (Request.Cookies.TryGetValue("selectedDate", out var selectedDate))
            {
                start = selectedDate;
            }
            int theartr = (int)SelectedTheaterId;
            int timeslot = (int) SelectedTimeSlotId;


            return RedirectToPage("/Users/Cart/Seats", new TicketDTO
            {
                start = start,
                theartr = theartr,
                timeslot = timeslot,
                movieId = movieId
            });
        }
    }
}

MovieBooker-backend/MovieBooker/Pages/Users/Movies/DetailMovie.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Dtos;

namespace MovieBooker.Pages.Users.Movies
{
    public class DetailMovieModel : PageModel
    {
        public List<MovieDto> moives { get; set; }
        public List<MovieImageDto> movieImages { get; set; }
        public List<MovieImageDto> m{ get; set; }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            HttpClient _httpClient = new HttpClient();
            var response = await _httpClient.GetAsync($"https://localhost:5000/api/movie?$filter=movieId eq {id}");
            if (response.IsSuccessStatusCode)
            {
                moives = await response.Content.ReadFromJsonAsync<List<MovieDto>>();
            }

            var response2 = await _httpClient.GetAsync($"https://localhost:5000/api/MovieImage");
            if (response2.IsSuccessStatusCode)
            {
                m = await response2.Content.ReadFromJsonAsync<List<MovieImageDto>>();
                movieImages = m.Where(s => s.MovieId  == id).ToList();
            }
            return Page();
        }

       
    }
}

MovieBooker-backend/MovieBooker/Pages/Users/Cart/PayTicket.cshtml
@page
@model MovieBooker.Pages.Users.Cart.PayTicketModel
@{
}
<link rel="stylesheet" href="~/css/Payticket.css" asp-append-version="true" />
<div class="container">
    <h1>THANH TOÁN</h1>
    <form method="post">
    @foreach (var sch in Model.schedules)
    {
        <div class="main-content">
            <div class="left-column">
@*                <div class="section discount-section">
                    <div class="section-header">
                        <span>Bước 1: GIẢM GIÁ</span>
                        <button class="reset-button">Đặt lại</button>
                    </div>
                    <div class="discount-options">
                        <label><input type="radio" name="discount"> CGV Voucher</label>
                        <label><input type="radio" name="discount"> Mã giảm giá</label>
                        <label><input type="radio" name="discount"> Điểm CGV</label>
                        <label><input type="radio" name="discount"> Đối tác</label>
                        <label><input type="radio" name="discount"> Mã Khuyến Mãi</label>
                    </div>
                </div>*@

                <div class="section gift-section">
                    <div class="section-header">
                        <span>Bước 1: Email xác nhận</span>
                    </div>
                        <label><input type="text" name="confirmemail" placeholder="Email" style=" width: 50%;" required></label>
                </div>

                <div class="section payment-method-section">
                    <div class="section-header">
                        <span>Bước 2: HÌNH THỨC THANH TOÁN</span>
                    </div>
    @*                <label><input type="radio" name="payment"> ATM card (Thẻ nội địa)</label>
                    <label><input type="radio" name="payment"> Thẻ quốc tế (Visa, Master, Amex, JCB)</label>
                    <label><input type="radio" name="payment"> MoMo: Nhập MM24 - 5K, nhận thẻ 10k 4G/5G</label>*@
                        <div class="payment-options">
                            <label class="payment-option">
                                <input type="radio" name="payment" value="paypal" required>
                                <img src="https://upload.wikimedia.org/wikipedia/commons/a/a4/Paypal_2014_logo.png" alt="PayPal Logo" class="payment-logo">
                                PayPal
                            </label>
                            <label class="payment-option">
                                <input type="radio" name="payment" value="vnpay" required>
                                <img src="https://vinadesign.vn/uploads/images/2023/05/vnpay-logo-vinadesign-25-12-57-55.jpg" alt="VNPAY Logo" class="payment-logo">
                                VNPAY
                            </label>
                        </div>
                </div>
            </div>

            <div class="right-column">
                <div class="total-section">
                    <div class="total-label">Tổng cộng</div>
                    @if (TempData["totalprice"] != null)
                    {
                        double totalprice = (double)TempData["totalprice"];
                        <div class="total-value">@totalprice VND</div>

                        <div class="total-label">Khuyến mãi</div>
                        <div class="total-value">0,00 đ</div>
                        <div class="total-label red">Tổng số tiền thanh toán</div>
                        <div class="total-value red">@totalprice VND</div>
                    }
                </div>

                <div class="footer">
                    <label><input required type="checkbox" name="terms"> Tôi đồng ý với điều khoản sử dụng và mua vé cho người có độ tuổi phù hợp</label>
                </div>
            </div>
        </div>

        <div class="movie-info">
            <img src="@sch.movieImage" alt="Movie Poster">
            <div class="movie-details">
                <div class="movie-title">@sch.MovieTitle</div>
                <div class="movie-time">@sch.TheaterName @sch.TimeSlot, @sch.ScheduleDate.Value.ToString("dd/MM/yyyy")</div>
                @{
                    var groupedSeats = Model.seats
                    .GroupBy(seat => seat.SeatTypeName)
                    .ToDictionary(g => g.Key, g => g.Select(seat => seat.SeatNumber).ToList());
                }
                @foreach (var seatGroup in groupedSeats)
                {
                    <div class="movie-seat">
                       Ghế @seatGroup.Key: @string.Join(", ", seatGroup.Value)
                    </div>
                }
                @if (TempData["totalprice"] != null)
                {
                    double totalprice = (double)TempData["totalprice"];
                    <div class="movie-price">Tổng: @totalprice VND</div>
                    <input type="hidden" value="@totalprice" name="totalprice" />
                }
            </div>
            <input type="hidden" value="@sch.TimeSlotId" name="timeslotid">
            <input type="hidden" value="@sch.MovieId" name="movieid">
            <input type="hidden" value="@sch.ScheduleDate" name="resdate">
            <input type="hidden" value="@sch.SchedulesId" name="schedulesId"/>
            <button type="submit" asp-page-handler="Payment" class="payment-button">PAYMENT</button>
        </div>
    }
    </form>
</div>

MovieBooker-backend/MovieBooker/Pages/Users/Cart/Ticket.cshtml
@page
@model MovieBooker.Pages.Users.Cart.TicketModel
@{
    Layout = null;
    int? idmovie = (int)TempData["movieId"];
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Showtimes</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="~/css/Ticket.css" asp-append-version="true" />
</head>
<body>
    <div class="header">
        <a asp-page="/Users/Movies/DetailMovie" asp-route-id="@idmovie" class="back-button"><i class="fas fa-times"></i></a>
    </div>
    <div class="container">
        <div class="date-picker">
            <div class="dates">
                @foreach (var date in Model.SelectedDates)
                {
                    <a asp-page-handler="Schedule" asp-route-selectedate="@date" asp-route-movieId="@idmovie" style="text-decoration:none; color:black">
                        <div id="date-@date.ToString("yyyyMMdd")" class="date"
                             data-date="@date.ToString("yyyy-MM-dd")" onclick="selectDate(this)">
                            <span>@date.ToString("MM ddd")</span><br>
                            @date.Day
                        </div>
                    </a>
                }
            </div>
        </div>
        <div class="location-picker">
            <div class="location active">Hà Nội</div>
        </div>

        <form method="post" onsubmit="return validateForm()">
            <div class="showtimes">
                @{
                    int count = 0;
                }
                @foreach (var theater in Model.theaters)
                {
                    <div class="cinema">
                        <h3>@theater.TheaterName</h3>
                        <div class="times" data-theater-id="@theater.TheaterId">

                            @foreach (var time in Model.schedules)
                            {
                                @if (time.TheaterId == theater.TheaterId)
                                {
                                    <span class="time" data-timeslot-id="@time.TimeSlotId"
                                          onclick="selectTime(this, @theater.TheaterId, @time.TimeSlotId)">@time.TimeSlot</span>
                                    count++;
                                }
                            }
                            @if (count == 0)
                            {
                                <span>Không có lịch chiếu</span>
                            }
                        </div>
                    </div>
                }
            </div>
            @if (count > 0)
            {
                <button style="background: linear-gradient(89deg, #5e7188, #3e4b5b); border: 0;
    transition: opacity 0.3s ease;
    font-size: 0.875rem;
    line-height: 1;
    font-family: 'ubuntu-bold', sans-serif;
                        min-width: 100px;
                        color: #ffffff;
                        height: 35px;" type="submit">
                    Next
                </button>
                <input type="hidden" name="SelectedTheaterId" id="selectedTheaterId" />
                <input type="hidden" name="SelectedTimeSlotId" id="selectedTimeSlotId" />
                <input type="hidden" name="movieId" value="@idmovie" />
            }
        </form>
    </div>
</body>
</html>
<script>
    // Hàm để thiết lập cookie
    function setCookie(name, value, days) {
        var expires = "";
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            expires = "; expires=" + date.toUTCString();
        }
        document.cookie = name + "=" + (value || "") + expires + "; path=/";
    }

    // Hàm để lấy giá trị của cookie
    function getCookie(name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') c = c.substring(1, c.length);
            if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
        }
        return null;
    }

    document.addEventListener('DOMContentLoaded', function () {
        // Kiểm tra xem đã lưu trữ ngày được chọn trong cookie chưa
        var selectedDate = getCookie('selectedDate');
        if (selectedDate) {
            // Tìm div có data-date tương ứng với selectedDate và thêm lớp 'active'
            var selectedDiv = document.querySelector('.date[data-date="' + selectedDate + '"]');
            if (selectedDiv) {
                selectedDiv.classList.add('active');
            }
        }
    });

    function selectDate(selectedDiv) {
        // Lấy ngày tương ứng từ thuộc tính data-date của div được nhấp vào
        var selectedDate = selectedDiv.getAttribute('data-date');

        // Xóa lớp 'active' khỏi tất cả các div có class 'date'
        document.querySelectorAll('.date').forEach(function (el) {
            el.classList.remove('active');
        });

        // Thêm lớp 'active' vào div được nhấp vào
        selectedDiv.classList.add('active');
        // Lưu trữ ngày được chọn vào cookie
        setCookie('selectedDate', selectedDate, 7);
    }

    function selectTime(selectedTimeDiv, theaterId, timeSlotId) {
        if (selectedTimeDiv.classList.contains('active')) {
            selectedTimeDiv.classList.remove('active');
            document.getElementById('selectedTheaterId').value = '';
            document.getElementById('selectedTimeSlotId').value = '';
        } else {
            document.querySelectorAll('.time').forEach(function (el) {
                el.classList.remove('active');
            });
            selectedTimeDiv.classList.add('active');
            document.getElementById('selectedTheaterId').value = theaterId;
            document.getElementById('selectedTimeSlotId').value = timeSlotId;
        }
    }
    function validateForm() {
        var selectedTheaterId = document.getElementById('selectedTheaterId').value;
        var selectedTimeSlotId = document.getElementById('selectedTimeSlotId').value;

        if (!selectedTheaterId || !selectedTimeSlotId) {
            alert("Vui lòng chọn thời gian");
            return false;
        }
        return true;
    }
</script>