MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieBooker.Pages.Admin.Movie
{
	public class DeleteModel : PageModel
	{
		private readonly IHttpClientFactory _httpClientFactory;

		public DeleteModel(IHttpClientFactory httpClientFactory)
		{
			_httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
		}

		public async Task<IActionResult> OnPostAsync(int id, string publicId, int movieId)
		{
			try
			{
				if (string.IsNullOrEmpty(publicId))
				{
					throw new ArgumentNullException(nameof(publicId), "Public ID is required.");
				}

				string encodedPublicId = Uri.EscapeDataString(publicId);

				using (var client = _httpClientFactory.CreateClient())
				{
					// Delete image on Cloudinary
					var responseOnCloud = await client.DeleteAsync($"https://localhost:5000/api/Images/{encodedPublicId}");
					responseOnCloud.EnsureSuccessStatusCode();

					// Read response from Cloudinary API
					var cloudResponseContent = await responseOnCloud.Content.ReadAsStringAsync();
					if (!cloudResponseContent.ToLower().Contains("ok"))
					{
						throw new Exception("Failed to delete image on Cloudinary.");
					}

					// Delete image in Database
					var responseRemoveOnData = await client.DeleteAsync($"https://localhost:5000/api/MovieImage/{id}");
					responseRemoveOnData.EnsureSuccessStatusCode();
				}

				return RedirectToPage("/Admin/Movie/Edit", new { id = movieId });
			}
			catch (Exception ex)
			{
				// Log or handle the exception
				Console.WriteLine($"Exception: {ex.Message}");
				return RedirectToPage("/Admin/Movie/Edit", new { id = movieId });
			}
		}

		public async Task<IActionResult> OnPostDeleteHandler(int id)
		{
			using (var client = _httpClientFactory.CreateClient())
			{
				var response = await client.DeleteAsync($"https://localhost:5000/api/Movie/{id}");
				response.EnsureSuccessStatusCode();
			}
			return RedirectToPage("/Admin/Movie/Index");
		}
	}
}

MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Dtos;
using System.Net.Http;

namespace MovieBooker.Pages.Admin.Movie
{
    public class DetailModel : PageModel
    {
		private readonly IHttpClientFactory _httpClientFactory;
		private readonly ILogger<EditModel> _logger;

		public DetailModel(IHttpClientFactory httpClientFactory, ILogger<EditModel> logger)
		{
			_httpClientFactory = httpClientFactory;
			_logger = logger;
		}

		[BindProperty]
		public MovieDto movie { get; set; }

		public async Task<IActionResult> OnGetDetailHandler(int? id)
		{
			if (id == null)
			{
				_logger.LogError("Movie ID is null.");
				return RedirectToPage("/Admin/Movie/Index");
			}

			var httpClient = _httpClientFactory.CreateClient();

			try
			{
				movie = await FetchMovieAsync(httpClient, id.Value);
				return Page();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occurred while fetching movie data.");
				return Page();
			}
		}

		private async Task<MovieDto> FetchMovieAsync(HttpClient httpClient, int id)
		{
			var apiUrl = $"https://localhost:5000/api/movie?filter=MovieId eq {id}";
			var response = await httpClient.GetAsync(apiUrl);

			if (!response.IsSuccessStatusCode)
			{
				throw new HttpRequestException($"Failed to fetch movie with ID {id}");
			}

			var movies = await response.Content.ReadFromJsonAsync<List<MovieDto>>();
			if (movies == null || movies.Count != 1)
			{
				throw new Exception($"Movie with ID {id} not found or multiple entries returned.");
			}

			return movies.First();
		}
	}
}

MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Dtos;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace MovieBooker.Pages.Admin.Movie
{
	public class EditModel : PageModel
	{
		private readonly IHttpClientFactory _httpClientFactory;
		private readonly ILogger<EditModel> _logger;

		public EditModel(IHttpClientFactory httpClientFactory, ILogger<EditModel> logger)
		{
			_httpClientFactory = httpClientFactory;
			_logger = logger;
		}

		[BindProperty]
		public MovieDto movie { get; set; }
		public List<VideoDetailDto> VideoDetails { get; set; }
		public List<MovieCategoryDto> MovieCategories { get; set; }
		public List<MovieStatusDto> MovieStatuses { get; set; }
		public List<MovieImageDto> Images { get; set; }
		public IFormFileCollection NewImages { get; set; }

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (id == null)
			{
				_logger.LogError("Movie ID is null.");
				return RedirectToPage("/Admin/Movie/Index");
			}

			var httpClient = _httpClientFactory.CreateClient();

			try
			{
				movie = await FetchMovieAsync(httpClient, id.Value);
				var fetchTasks = new List<Task>
				{
					FetchVideoDetailsAsync(httpClient),
					FetchMovieCategoriesAsync(httpClient),
					FetchMovieStatusesAsync(httpClient),
					FetchMovieImagesAsync(httpClient)
				};

				await Task.WhenAll(fetchTasks);

				return Page();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occurred while fetching movie data.");
				return RedirectToPage("/Admin/Movie/Index");
			}
		}

		public async Task<IActionResult> OnPostAsync()
		{
			var httpClient = _httpClientFactory.CreateClient();

			try
			{
				if (movie == null)
				{
					throw new Exception("Movie object is null");
				}

				await UpdateMovieAsync(httpClient, movie);
				var images = await UploadImagesAsync(httpClient, NewImages);

				if (images == null) throw new Exception("Image upload failed");

				await InsertImagesAsync(httpClient, images, movie.MovieId);

				return RedirectToPage("/Admin/Movie/Edit", new { id = movie.MovieId });
			}
			catch (Exception ex)
			{
				// Log the exception (ex) here if needed
				return RedirectToPage("/Admin/Movie/Edit", new { id = movie.MovieId });
			}
		}
		private async Task UpdateMovieAsync(HttpClient httpClient, MovieDto movie)
		{
			var updateMovie = new
			{
				MovieId = movie.MovieId,
				movieTitle = movie.MovieTitle,
				description = movie.Description,
				price = movie.Price,
				director = movie.Director,
				durations = movie.Durations,
				trailer = movie.Trailer,
				releaseDate = movie.ReleaseDate,
				categoryId = movie.CategoryId,
				statusId = movie.StatusId
			};

			string jsonUpdateMovie = JsonSerializer.Serialize(updateMovie);
			var requestMovie = new HttpRequestMessage(HttpMethod.Put, "https://localhost:5000/api/Movie")
			{
				Headers = { { "accept", "*/*" } },
				Content = new StringContent(jsonUpdateMovie, Encoding.UTF8, "application/json")
			};

			var responseUpdateMovie = await httpClient.SendAsync(requestMovie);
			responseUpdateMovie.EnsureSuccessStatusCode();
		}
		private async Task<List<ImageDto>> UploadImagesAsync(HttpClient httpClient, IEnumerable<IFormFile> newImages)
		{
			var requestUploadImage = new HttpRequestMessage(HttpMethod.Post, "https://localhost:5000/api/Images/upload")
			{
				Headers = { { "accept", "*/*" } }
			};

			var contentUploadImage = new MultipartFormDataContent();

			foreach (var formFile in newImages)
			{
				if (formFile.Length > 0)
				{
					var streamContent = new StreamContent(formFile.OpenReadStream());
					contentUploadImage.Add(streamContent, "files", formFile.FileName);
				}
			}

			requestUploadImage.Content = contentUploadImage;
			var responseUploadImage = await httpClient.SendAsync(requestUploadImage);
			responseUploadImage.EnsureSuccessStatusCode();

			return await responseUploadImage.Content.ReadFromJsonAsync<List<ImageDto>>();
		}

		private async Task InsertImagesAsync(HttpClient httpClient, IEnumerable<ImageDto> images, int movieId)
		{
			foreach (var image in images)
			{
				var newMovieImage = new MovieImageDto
				{
					MovieId = movieId,
					LinkImage = image.secureUrl,
					PublicId = image.publicId
				};

				string jsonPostImage = JsonSerializer.Serialize(newMovieImage);
				var requestPostImage = new HttpRequestMessage(HttpMethod.Post, "https://localhost:5000/api/MovieImage")
				{
					Headers = { { "accept", "*/*" } },
					Content = new StringContent(jsonPostImage, Encoding.UTF8, "application/json")
				};

				var responsePostImage = await httpClient.SendAsync(requestPostImage);
				responsePostImage.EnsureSuccessStatusCode();
			}
		}

		private async Task<MovieDto> FetchMovieAsync(HttpClient httpClient, int id)
		{
			var apiUrl = $"https://localhost:5000/api/movie?filter=MovieId eq {id}";
			var response = await httpClient.GetAsync(apiUrl);

			if (!response.IsSuccessStatusCode)
			{
				throw new HttpRequestException($"Failed to fetch movie with ID {id}");
			}

			var movies = await response.Content.ReadFromJsonAsync<List<MovieDto>>();
			if (movies == null || movies.Count != 1)
			{
				throw new Exception($"Movie with ID {id} not found or multiple entries returned.");
			}

			return movies.First();
		}

		private async Task FetchVideoDetailsAsync(HttpClient httpClient)
		{
			var apiUrl = "https://localhost:5000/api/Video";
			var response = await httpClient.GetAsync(apiUrl);

			if (!response.IsSuccessStatusCode)
			{
				throw new HttpRequestException("Failed to fetch video details.");
			}

			VideoDetails = await response.Content.ReadFromJsonAsync<List<VideoDetailDto>>()
						   ?? new List<VideoDetailDto>();
		}

		private async Task FetchMovieCategoriesAsync(HttpClient httpClient)
		{
			var apiUrl = "https://localhost:5000/api/MovieCategory";
			var response = await httpClient.GetAsync(apiUrl);

			if (!response.IsSuccessStatusCode)
			{
				throw new HttpRequestException("Failed to fetch movie categories.");
			}

			MovieCategories = await response.Content.ReadFromJsonAsync<List<MovieCategoryDto>>()
							  ?? new List<MovieCategoryDto>();
		}

		private async Task FetchMovieStatusesAsync(HttpClient httpClient)
		{
			var apiUrl = "https://localhost:5000/api/MovieStatus";
			var response = await httpClient.GetAsync(apiUrl);

			if (!response.IsSuccessStatusCode)
			{
				throw new HttpRequestException("Failed to fetch movie statuses.");
			}

			MovieStatuses = await response.Content.ReadFromJsonAsync<List<MovieStatusDto>>()
							?? new List<MovieStatusDto>();
		}

		private async Task FetchMovieImagesAsync(HttpClient httpClient)
		{
			var apiUrl = "https://localhost:5000/api/MovieImage";
			var response = await httpClient.GetAsync(apiUrl);

			if (!response.IsSuccessStatusCode)
			{
				throw new HttpRequestException("Failed to fetch movie images.");
			}

			Images = await response.Content.ReadFromJsonAsync<List<MovieImageDto>>()
					 ?? new List<MovieImageDto>();
		}
	}
}

MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Dtos;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MovieBooker.Pages.Admin.Movie
{
    public class IndexModel : PageModel
    {
        private readonly HttpClient _httpClient;

        public IndexModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public List<MovieDto> Movies { get; set; }

        public int NumMovies { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; } = 10;
        public string KeySearch { get; set; }
        public string SortBy { get; set; }
        public string SortOrder { get; set; } = "asc";

        public async Task OnGet(string keySearch, int currentPage = 1, string sortBy = "MovieId", string sortOrder = "asc")
        {
            CurrentPage = currentPage;
            KeySearch = keySearch;
            SortBy = sortBy;
            SortOrder = sortOrder;

            var query = string.IsNullOrWhiteSpace(keySearch) ? "" : $"$filter=contains(tolower(movieTitle), '{keySearch.ToLower()}')";

            // Get count of filtered movies
            var countResponse = await _httpClient.GetAsync($"https://localhost:5000/odata/Movie/$count?{query}");
            if (countResponse.IsSuccessStatusCode)
            {
                var numMovieString = await countResponse.Content.ReadAsStringAsync();
                NumMovies = int.TryParse(numMovieString, out int count) ? count : 0;
            }

            int skip = (currentPage - 1) * PageSize;
            int top = PageSize;

            // Get sorted and paginated movies
            var sortParameter = $"{SortBy} {(SortOrder == "asc" ? "asc" : "desc")}";
            var dataResponse = await _httpClient.GetAsync($"https://localhost:5000/api/Movie?{query}&$top={top}&$skip={skip}&$orderby={sortParameter}");
            if (dataResponse.IsSuccessStatusCode)
            {
                Movies = await dataResponse.Content.ReadFromJsonAsync<List<MovieDto>>();
            }
        }
    }

}

MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Delete.cshtml
@page
@model MovieBooker.Pages.Admin.Movie.DeleteModel
@{
}

MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Detail.cshtml
@page
@model MovieBooker.Pages.Admin.Movie.DetailModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using MovieBooker.Dtos
@{
	ViewData["Title"] = "Movie Detail";
	Layout = "_AdminLayout";
}
<style>
	.image-gallery {
		display: flex;
		overflow-x: auto;
		gap: 10px;
		white-space: nowrap;
	}

	.image-item {
		position: relative;
		flex: 0 0 auto;
		margin-right: 10px;
	}

		.image-item img {
			width: 150px;
			height: 200px;
			object-fit: cover;
			display: block;
		}

	.form-group {
		margin-bottom: 20px;
	}

	.scroll-view {
		overflow-x: auto;
	}

</style>
<div class="content-wrapper">
	<div class="row">
		<div class="col-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<div class="form-group">
						<a asp-page="/admin/movie/index">
							<i class="fa fa-mail-reply" style="font-size: 20px; color: #b66dff" ;"></i>
						</a>
					</div>
					<div class="form-group">
						<label>Image</label>
						<br />
						@if(Model.movie.MovieImages == null || Model.movie.MovieImages.Count == 0)
						{
							<input type="text" class="form-control" placeholder="Movie do not have image" readonly>
						}
						else
						{
							<div class="image-gallery scroll-view">
								@foreach (var item in Model.movie.MovieImages)
								{
									<div class="image-item">
										<img src="@item.LinkImage" alt="Image Movie" width="150" height="200">
									</div>
								}
							</div>
						}
					</div>
					<div class="form-group">
						<label for="MovieTitle">Title</label>
						<input type="text" class="form-control" id="MovieTitle" placeholder="Title book" asp-for="@Model.movie.MovieTitle" readonly>
					</div>
					<div class="form-group">
						<label for="Description">Description</label>
						<input type="text" class="form-control" id="Description" placeholder="Description" asp-for="@Model.movie.Description" readonly>
					</div>
					<div class="form-group">
						<label for="Price">Price</label>
						<input type="number" class="form-control" id="Price" placeholder="Price" asp-for="@Model.movie.Price" readonly>
					</div>
					<div class="form-group">
						<label for="Director">Director</label>
						<input type="text" class="form-control" id="Director" placeholder="Director" asp-for="@Model.movie.Director" readonly>
					</div>
					<div class="form-group">
						<label for="Durations">Durations</label>
						<input type="text" class="form-control" id="Durations" placeholder="Durations" asp-for="@Model.movie.Durations" readonly>
					</div>
					<div class="form-group">
						<label for="ReleaseDate">Release Date</label>
						<input type="date" class="form-control" id="ReleaseDate" placeholder="ReleaseDate" asp-for="@Model.movie.ReleaseDate" readonly>
					</div>
					<div class="form-group">
						<label for="Category">Category</label>
						<input type="text" class="form-control" id="Category" placeholder="Category" asp-for="@Model.movie.Category.CategoryName" readonly>
					</div>
					<div class="form-group">
						<label for="Status">Status</label>
						<input type="text" class="form-control" id="Status" placeholder="Status" asp-for="@Model.movie.Status.StatusName" readonly>
					</div>
					<div class="form-group">
						<label for="Trailer">Trailer</label>
						<div class="input-group">
							@if (Model.movie.Trailer == null)
							{
								<input type="text" class="form-control" placeholder="Movie do not have trailer" readonly>
							}
							else
							{
								<iframe width="560" height="315" src="@Model.movie.Trailer" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="border: 10px solid black;"></iframe>
							}
						</div>
					</div>
					<form method="get" class="forms-sample" asp-page="/admin/movie/edit">
						<input type="hidden" name="id" asp-for="@Model.movie.MovieId" />
						<button type="submit" class="btn btn-gradient-primary me-2">Edit</button>
						<a asp-page="/admin/movie/index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

MovieBooker-backend/MovieBooker/Pages/Admin/Movie/Index.cshtml
@page
@model MovieBooker.Pages.Admin.Movie.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using MovieBooker.Dtos
@{
	ViewData["Title"] = "Manage Movies";
	Layout = "_AdminLayout";
}

<style>
	.table th img, .table td img {
		width: 100px;
		height: 100px;
		border-radius: 10%;
	}

	.table {
		text-align: center;
	}

		.table thead tr th a{
			text-decoration: none;
			color: black;
		}

	.paging {
		margin-top: 20px;
	}

	.form-group {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.search-box {
		display: flex;
		align-items: center;
	}

		.search-box input[type="search"] {
			border: 1px solid #ccc;
			border-radius: 4px 0 0 4px;
			padding: 10px;
			font-size: 16px;
			width: 300px;
			outline: none;
		}

		.search-box button {
			border: 1px solid #ccc;
			border-left: none;
			padding: 11px 20px;
			font-size: 16px;
			border-radius: 0 4px 4px 0;
			cursor: pointer;
			outline: none;
		}

			.search-box button:hover {
				background-color: #9a55ff;
			}
</style>


<div class="content-wrapper">
	<div class="row">
		<div class="col-12 grid-margin">
			<div class="card">
				<div class="card-body">
					<div class="form-group">
						<a asp-page="/admin/movie/insert"
						   class="btn btn-gradient-primary btn-icon-text"
						   style="font-size: 25px; padding: 5px 25px 5px 25px; font-family: monospace;">+</a>
						<div class="search-box">
							<input type="search" id="searchInput" value="@Model.KeySearch" placeholder="Nhập tên phim" />
							<button id="searchButton" class="btn btn-primary">
								<i class="fa fa-search"></i>
							</button>
						</div>
					</div>
					<div class="table-responsive">
						<table class="table">
							<thead>
								<tr>
									<th><a asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-sortBy="MovieId" asp-route-sortOrder="@(Model.SortOrder == "asc" ? "desc" : "asc")">Mã phim</a></th>
									<th>Hình ảnh</th>
									<th><a asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-sortBy="MovieTitle" asp-route-sortOrder="@(Model.SortOrder == "asc" ? "desc" : "asc")">Tên phim</a></th>
									<th><a asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-sortBy="Price" asp-route-sortOrder="@(Model.SortOrder == "asc" ? "desc" : "asc")">Giá</a></th>
									<th><a asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-sortBy="ReleaseDate" asp-route-sortOrder="@(Model.SortOrder == "asc" ? "desc" : "asc")">Ngày phát hành</a></th>
									<th><a asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-sortBy="StatusId" asp-route-sortOrder="@(Model.SortOrder == "asc" ? "desc" : "asc")">Trạng thái</a></th>
									<th>Hành động</th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model.Movies)
								{
									<tr>
										<td>@item.MovieId</td>
										<td>
											<a asp-page="/admin/movie/detail" asp-page-handler="DetailHandler" asp-route-id="@item.MovieId">
												@if (item.MovieImages.Any())
												{
													<img src="@item.MovieImages.First().LinkImage" alt="image" />
												}
												else
												{
													<p>No image available</p>
												}
											</a>
										</td>
										<td>@item.MovieTitle</td>
										<td>@item.Price VND</td>
										<td>@item.ReleaseDate?.ToString("dd/MM/yyyy")</td>
										<td>
											@switch (item.StatusId)
											{
												case 1:
													<label class="badge badge-gradient-info">@item.Status.StatusName</label>
													break;
												case 2:
													<label class="badge badge-gradient-success">@item.Status.StatusName</label>
													break;
												case 3:
													<label class="badge badge-gradient-danger">@item.Status.StatusName</label>
													break;
											}
										</td>
										<td>
											<form asp-page="/admin/movie/delete" asp-page-handler="DeleteHandler" asp-route-id="@item.MovieId" method="post" onsubmit="return confirmDelete()">
												<input type="hidden" asp-for="@item.MovieId" />
												@if (item.Enable == true)
												{
													<button type="submit" style="background: none; border: none; padding: 0; cursor: pointer;">
														<i class="fa fa-eye" style="font-size: 20px; color: #b66dff"></i>
													</button>
												}
												else
												{
													<button type="submit" style="background: none; border: none; padding: 0; cursor: pointer;">
														<i class="fa fa-eye-slash" style="font-size: 20px; color: #b66dff"></i>
													</button>
												}
											</form>
											<br />
											<a asp-page="/admin/movie/edit" asp-route-id="@item.MovieId">
												<i class="fa fa-pencil" style="margin-top: 10px; font-size: 20px; color: #b66dff"></i>
											</a>
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
					<div class="form-group d-flex justify-content-center align-items-center paging">
						<nav aria-label="Page navigation">
							<ul class="pagination">
								<li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
									<a class="page-link" asp-route-keySearch="@Model.KeySearch" asp-page="Index" asp-route-currentPage="@(Model.CurrentPage - 1)">&lt;</a>
								</li>
								@for (int i = 1; i <= (Model.NumMovies + Model.PageSize - 1) / Model.PageSize; i++)
								{
									<li class="page-item @(i == Model.CurrentPage ? "active" : "")">
										<a class="page-link" asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-currentPage="@i">@i</a>
									</li>
								}
								<li class="page-item @(Model.CurrentPage == (Model.NumMovies + Model.PageSize - 1) / Model.PageSize ? "disabled" : "")">
									<a class="page-link" asp-page="Index" asp-route-keySearch="@Model.KeySearch" asp-route-currentPage="@(Model.CurrentPage + 1)">&gt;</a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	function confirmDelete() {
		return confirm("Are you sure you want to hide this movie?");
	}

	document.addEventListener('DOMContentLoaded', function () {
		const searchInput = document.getElementById('searchInput');
		const searchButton = document.getElementById('searchButton');

		searchButton.addEventListener('click', function (event) {
			event.preventDefault();

			const query = encodeURIComponent(searchInput.value.trim());
			const baseUrl = '/admin/movie';
			const searchUrl = `${baseUrl}?keySearch=${query}&currentPage=1`;

			window.location.href = searchUrl;
		});
	});
</script>