MovieBooker-backend/MovieBooker/Pages/Admin/CreateSchedule.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Dtos;
using MovieBooker.Models;
using System.Net.Http;

namespace MovieBooker.Pages.Admin
{
    public class CreateScheduleModel : PageModel
    {
        public List<MovieDto> moives { get; set; }
        public List<TheaterDTO> theaters { get; set; }
        public List<TimeSlotDTO> TimeSlots { get; set; }
        public List<RoomDTO> Rooms { get; set; }
        public TimeSlotDTO TimeSlot { get; set; }

        [BindProperty]
        public CreateScheduleDTO Creates { get; set; }

        [BindProperty]
        public List<int> SelectedTimeSlotIds { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {

            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = await _httpClient.GetAsync("https://localhost:5000/api/Movie?$filter=statusId eq 1 or statusId eq 2");
            if (response.IsSuccessStatusCode)
            {
                moives = await response.Content.ReadFromJsonAsync<List<MovieDto>>();
            }

            HttpResponseMessage response2 = await _httpClient.GetAsync("https://localhost:5000/api/TimeSlot/GetAllTimeSlot");
            if (response2.IsSuccessStatusCode)
            {
                TimeSlots = await response2.Content.ReadFromJsonAsync<List<TimeSlotDTO>>();
            }

            HttpResponseMessage response3 = await _httpClient.GetAsync("https://localhost:5000/api/Theater/GetAllTheater");
            if (response3.IsSuccessStatusCode)
            {
                theaters = await response3.Content.ReadFromJsonAsync<List<TheaterDTO>>();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (SelectedTimeSlotIds == null || !SelectedTimeSlotIds.Any())
            {
                TempData["mess"] = "Please select at least one time slot.";
                return await OnGetAsync();
            }

            List<int> duplicateSchedules = new List<int>();
            List<string> duplicateSche = new List<string>();
            List<string> successfulSchedules = new List<string>();

            HttpClient _httpClient = new HttpClient();
            string rlDate = Creates.ScheduleDate.Value.ToString("yyyy-MM-dd");

            foreach (var timeSlotId in SelectedTimeSlotIds)
            {
                HttpResponseMessage response = await _httpClient.GetAsync($"https://localhost:5000/api/Schedule/CheckExistSchedule/{Creates.TheaterId}/{timeSlotId}/{rlDate}/{Creates.RoomId}");
                if (response.IsSuccessStatusCode)
                {
                    HttpResponseMessage response3 = await _httpClient.GetAsync($"https://localhost:5000/api/TimeSlot/GetTimeSlotById/{timeSlotId}");
                    if (response3.IsSuccessStatusCode)
                    {
                        TimeSlot = await response3.Content.ReadFromJsonAsync<TimeSlotDTO>();
                        duplicateSche.Add(TimeSlot.StartTime.ToString());
                        duplicateSchedules.Add(timeSlotId);
                    }
                }
            }

            foreach (var timeSlotId in SelectedTimeSlotIds.Except(duplicateSchedules))
            {
                Creates.TimeSlotId = timeSlotId;
                HttpResponseMessage response2 = await _httpClient.PostAsJsonAsync("https://localhost:5000/api/Schedule/CreateSchedule", Creates);
                if (response2.IsSuccessStatusCode)
                {
                    HttpResponseMessage response3 = await _httpClient.GetAsync($"https://localhost:5000/api/TimeSlot/GetTimeSlotById/{timeSlotId}");
                    if (response3.IsSuccessStatusCode)
                    {
                        TimeSlot = await response3.Content.ReadFromJsonAsync<TimeSlotDTO>();
                        successfulSchedules.Add(TimeSlot.StartTime.ToString());
                    }
                }
            }

            if (duplicateSche.Any())
            {
                TempData["exist"] = $"Some schedules already exist: {string.Join(", ", duplicateSche)}";
            }

            if (successfulSchedules.Any())
            {
                TempData["mess"] = $"Successfully created schedules: {string.Join(", ", successfulSchedules)}";
            }

            return await OnGetAsync();
        }
    }
}

MovieBooker-backend/MovieBooker/Pages/Admin/ManageSchedules.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Models;

namespace MovieBooker.Pages.Admin
{
    public class ManageSchedulesModel : PageModel
    {

        public List<ScheduleDTO> Schedules { get; set; }
        public List<TimeSlotDTO> TimeSlots { get; set; }

        [BindProperty]
        public SelectDateModel Input { get; set; }
        public List<DateTime> SelectedDates { get; set; }
        public async Task<IActionResult> OnGet()
        {
            DateTime startDate = DateTime.Today;
            DateTime endDate = DateTime.Today.AddDays(6);

            string start = startDate.ToString("yyyy-MM-dd");
            string end = endDate.ToString("yyyy-MM-dd");
            SelectedDates = InitializeDefaults(startDate, endDate);
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = await _httpClient.GetAsync($"https://localhost:5000/api/Schedule/GetSchedule?$filter=scheduleDate gt {start} and scheduleDate lt {end}");
            if (response.IsSuccessStatusCode)
            {
                Schedules = await response.Content.ReadFromJsonAsync<List<ScheduleDTO>>();
            }
            HttpResponseMessage response2 = await _httpClient.GetAsync("https://localhost:5000/api/TimeSlot/GetAllTimeSlot");
            if (response2.IsSuccessStatusCode)
            {
                TimeSlots = await response2.Content.ReadFromJsonAsync<List<TimeSlotDTO>>();
            }
            return Page();  
        }

        public async Task<IActionResult> OnPostAsync()
        {
            DateTime startDate = Input.StartDate;
            DateTime endDate = Input.EndDate;
            // Lấy danh sách các ngày trong khoảng thời gian từ startDate đến endDate
            SelectedDates = GetDatesInRange(startDate, endDate);

            string start = startDate.ToString("yyyy-MM-dd");
            string end = endDate.ToString("yyyy-MM-dd");
            HttpClient _httpClient = new HttpClient();

            HttpResponseMessage response = await _httpClient.GetAsync($"https://localhost:5000/api/Schedule/GetSchedule?$filter=scheduleDate gt {start} and scheduleDate lt {end}");
            if (response.IsSuccessStatusCode)
            {
                Schedules = await response.Content.ReadFromJsonAsync<List<ScheduleDTO>>();
            }

            HttpResponseMessage response2 = await _httpClient.GetAsync("https://localhost:5000/api/TimeSlot/GetAllTimeSlot");
            if (response2.IsSuccessStatusCode)
            {
                TimeSlots = await response2.Content.ReadFromJsonAsync<List<TimeSlotDTO>>();
            }

            return Page();
        }
        private List<DateTime> GetDatesInRange(DateTime startDate, DateTime endDate)
        {
            List<DateTime> datesInRange = new List<DateTime>();
            for (DateTime date = startDate; date <= endDate; date = date.AddDays(1))
            {
                datesInRange.Add(date);
            }
            return datesInRange;
        }
        private List<DateTime> InitializeDefaults(DateTime startDate, DateTime endDate)
        {
            List<DateTime> datesInRange = new List<DateTime>();
            for (DateTime date = startDate; date <= endDate; date = date.AddDays(1))
            {
                datesInRange.Add(date);
            }
            return datesInRange;
        }
        public async Task<IActionResult> OnGetCreateScheduleAsync()
        {
            return RedirectToPage("/Admin/CreateSchedule");
        }

        public class SelectDateModel
        {
            public DateTime StartDate { get; set; }
            public DateTime EndDate { get; set; }
        }
    }
}

MovieBooker-backend/MovieBooker/Pages/Admin/ManageUsers.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieBooker.Models;
using StackExchange.Redis;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Headers;

namespace MovieBooker.Pages.Admin
{
    //[Authorize]
    public class ManageUsersModel : PageModel
    {
        private readonly IAuthenService _authenticationService;
        public ManageUsersModel(IAuthenService authenticationService)
        {
            _authenticationService = authenticationService;
        }
        public List<UserDTO> Users { get; set; }
        public int PageSize { get; } = 5;
        public int PageIndex { get; set; } = 1;

        public int TotalItemsCustomer { get; set; }
        public int TotalItemsStaff { get; set; }

        public async Task<IActionResult> OnGetAsync(int pageIndex = 1)
        {
            HttpClient _httpClient = new HttpClient();
            var accessToken = await _authenticationService.GetAccessTokenAsync();

            if (!string.IsNullOrEmpty(accessToken))
            {

                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var handler = new JwtSecurityTokenHandler();
                var jwtToken = handler.ReadToken(accessToken) as JwtSecurityToken;
                var roleClaim = jwtToken.Claims.FirstOrDefault(claim => claim.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role")?.Value;
                if (roleClaim == "Admin")
                {
                    PageIndex = pageIndex;
                    HttpResponseMessage response = await _httpClient.GetAsync($"https://localhost:5000/api/User/GetAllUser?$filter=roleId eq 3&$top={PageSize}&$skip={(PageIndex - 1) * PageSize}");
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["User"] = "Customer";
                        Users = await response.Content.ReadFromJsonAsync<List<UserDTO>>();

                        HttpResponseMessage responseTotalNotSeen = await _httpClient.GetAsync($"https://localhost:5000/odata/User/$count?$filter=roleId eq 3");
                        if (responseTotalNotSeen.IsSuccessStatusCode)
                        {
                            TotalItemsCustomer = await responseTotalNotSeen.Content.ReadFromJsonAsync<int>();
                        }

                    }
                    else
                    {
                        return RedirectToPage("/Error");
                    }
                }
                else
                {
                    return RedirectToPage("/AccessDenied");
                }
            }
            else
            {
                return RedirectToPage("/AccessDenied");
            }
            return Page();
        }

        public async Task<IActionResult> OnGetStaffAsync(int pageIndex = 1)
        {
            HttpClient _httpClient = new HttpClient();
            var accessToken = await _authenticationService.GetAccessTokenAsync();

            if (!string.IsNullOrEmpty(accessToken))
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                HttpResponseMessage response = await _httpClient.GetAsync($"https://localhost:5000/api/User/GetAllUser?$filter=roleId eq 2&$top={PageSize}&$skip={(PageIndex - 1) * PageSize}");
                if (response.IsSuccessStatusCode)
                {
                    PageIndex = pageIndex;
                    Users = await response.Content.ReadFromJsonAsync<List<UserDTO>>();
                    TempData["User"] = "Staff";

                    HttpResponseMessage responseTotalNotSeen = await _httpClient.GetAsync($"https://localhost:5000/odata/User/$count?$filter=roleId eq 2");
                    if (responseTotalNotSeen.IsSuccessStatusCode)
                    {
                        TotalItemsStaff = await responseTotalNotSeen.Content.ReadFromJsonAsync<int>();
                    }

                }
                else
                {
                    return RedirectToPage("/AccessDenied");
                }
            }
            else
            {
                return RedirectToPage("/AccessDenied");
            }
            return Page();
        }

        public async Task<IActionResult> OnGetChangeStatusUserAsync(int id, string check)
        {
            HttpClient _httpClient = new HttpClient();
            var accessToken = await _authenticationService.GetAccessTokenAsync();
            if (!string.IsNullOrEmpty(accessToken))
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                HttpResponseMessage response = await _httpClient.PutAsync($"https://localhost:5000/api/User/ChangeStatusUser/{id}",null);
                if (response.IsSuccessStatusCode)
                {
                    if (check == "Customer")
                    {
                        return RedirectToPage(new { handler = "OnGet" });
                    }
                    else
                    {
                        return RedirectToPage(new { handler = "Staff" });
                    }
                }

                else
                {
                    return Page();
                }
            }
            else
            {
                return RedirectToPage("/AccessDenied");
            }          
        }

        public async Task<IActionResult> OnPostAsync(string check, string search)
        {
            HttpClient _httpClient = new HttpClient();
            var accessToken = await _authenticationService.GetAccessTokenAsync();
            if (!string.IsNullOrEmpty(accessToken))
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                if(check == "Customer")
                {

                    HttpResponseMessage response =
                await _httpClient.GetAsync($"https://localhost:5000/api/User/GetAllUser?$filter=roleId " +
                "eq 3 and (contains(userName, '"+search+"') or contains(email, '"+search+"') or contains(phoneNumber, '"+search+"') " +
                "or contains(address, '"+search+"'))");
                    if (response.IsSuccessStatusCode)
                    {
                        Users = await response.Content.ReadFromJsonAsync<List<UserDTO>>();
                        TempData["User"] = "Customer";
                    }
                }
                else
                {
                    HttpResponseMessage response =
                        await _httpClient.GetAsync($"https://localhost:5000/api/User/GetAllUser?$filter=roleId " +
                        "eq 2 and (contains(userName, '" + search + "') or contains(email, '" + search + "') or contains(phoneNumber, '" + search + "') " +
                        "or contains(address, '" + search + "'))");
                    if (response.IsSuccessStatusCode)
                    {
                        Users = await response.Content.ReadFromJsonAsync<List<UserDTO>>();
                        TempData["User"] = "Staff";
                    }
                }
            }
            else
            {
                return RedirectToPage("/AccessDenied");
            }
            return Page();
        }
    }
}

MovieBooker-backend/MovieBooker/Pages/Admin/CreateSchedule.cshtml
@page
@model MovieBooker.Pages.Admin.CreateScheduleModel
@{
    Layout = "_AdminLayout";
}
<style>
    .time-slot-container {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
    }
    .time-slot-item {
        flex: 1 1 16%;
        box-sizing: border-box;
    }
</style>

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Tạo lịch chiếu phim</h4>
            <form method="post">
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Chọn rạp chiếu</label>
                    <select required asp-for="Creates.TheaterId" class="form-select form-select-lg" id="exampleFormControlSelect1" style="color:black" onchange="loadRooms(this.value)">
                        <option value="">Chọn rạp chiếu</option>
                        @foreach (var item in Model.theaters)
                        {
                            <option value="@item.TheaterId">@item.TheaterName</option>
                        }
                    </select>
                </div>
                <div class="form-group" id="roomSelectDiv" style="display:none;">
                    <label for="exampleFormControlSelect4">Chọn phòng chiếu</label>
                    <select required asp-for="Creates.RoomId" class="form-select form-select-lg" id="exampleFormControlSelect4" style="color:black">
                        <option value="">Chọn phòng chiếu</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect2">Chọn phim</label>
                    <select asp-for="Creates.MovieId" class="form-select" id="exampleFormControlSelect2" style="color:black">
                        @foreach (var item in Model.moives)
                        {
                            <option value="@item.MovieId">@item.MovieTitle</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label>Chọn khung giờ</label>
                    <div id="timeSlotsContainer" class="time-slot-container">
                        @foreach (var item in Model.TimeSlots)
                        {
                            <div class="time-slot-item">
                                <input class="form-check-input" type="checkbox" value="@item.TimeSlotId" id="timeSlot@item.TimeSlotId" name="SelectedTimeSlotIds" />
                                <label class="form-check-label" for="timeSlot@item.TimeSlotId" style="padding-top: 5px;">
                                    @item.StartTime
                                </label>
                            </div>
                        }
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect3">Select Date</label>
                    <input asp-for="Creates.ScheduleDate" type="date" class="form-control form-control-sm" aria-label="Username" required />
                </div>
                @if (TempData["mess"] != null)
                {
                    <p style="color:forestgreen">@TempData["mess"]</p>
                }
                @if (TempData["exist"] != null)
                {
                    <p style="color:red">@TempData["exist"]</p>
                }
                <button type="submit" class="btn btn-gradient-primary me-2">Create Schedule</button>
            </form>
        </div>
    </div>
</div>

<script>
    function loadRooms(theaterId) {
        if (theaterId) {
            $.ajax({
                url: `https://localhost:5000/api/Room/GetRoom/${theaterId}`,
                type: 'GET',
                success: function (data) {
                    var roomSelect = $('#exampleFormControlSelect4');
                    roomSelect.empty();
                    roomSelect.append('<option value="">Select Room</option>');
                    if (data.length > 0) {
                        data.forEach(function (room) {
                            roomSelect.append(`<option value="${room.roomId}">${room.roomNumber}</option>`);
                        });
                        $('#roomSelectDiv').show();
                    } else {
                        $('#roomSelectDiv').hide();
                        roomSelect.append('<option value="">No Rooms Available</option>');
                    }
                },
                error: function (xhr, status, error) {
                    console.error('AJAX Error:', status, error);
                    $('#roomSelectDiv').hide();
                }
            });
        } else {
            $('#roomSelectDiv').hide();
        }
    }
</script>

MovieBooker-backend/MovieBooker/Pages/Admin/ManageUsers.cshtml
@page
@model MovieBooker.Pages.Admin.ManageUsersModel
@{
    Layout = "_AdminLayout";
}

<link rel="stylesheet" href="~/css/ManageUser.css" asp-append-version="true" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round" asp-append-version="true">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" asp-append-version="true">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" asp-append-version="true">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" asp-append-version="true">
<script src="https://code.jquery.com/jquery-3.5.1.min.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" asp-append-version="true"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" asp-append-version="true"></script>
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous" asp-append-version="true"></script>



<div class="container-xl">
    <div class="table-responsive">
        @if (TempData["User"] == "Customer") {
            <div class="search-field d-none d-md-block" style="margin-bottom: 5px;">
                <form class="d-flex align-items-center h-100" method="post">
                <button type="submit" class="input-group-prepend bg-transparent">
                    <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </button>
                    <input type="hidden" name="check" value="Customer">
                <input type="text" name="search" class="form-control bg-transparent border-0" placeholder="Tìm kiếm" style="width: 96%">
            </form>
            </div>
        }
        else
        {
            <div class="search-field d-none d-md-block" style="margin-bottom: 5px;">
                <form class="d-flex align-items-center h-100" method="post">
                    <button type="submit" class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </button>
                    <input type="hidden" name="check" value="Staff">
                    <input type="text" name="search" class="form-control bg-transparent border-0" placeholder="Tìm kiếm" style="width: 96%">
                </form>
            </div>
        }

        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>Quản lý <b>Người dùng</b></h2>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Mã người dùng</th>
                        <th>Avatar</th>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Vai trò</th>
                        <th>Trạng thái</th>
                        <th>Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Users)
                    {
                        <tr>
                            <td>@item.UserId</td>
                            <td>
                                <a href="#">
                                    <img style="width: 30px; height: 30px;"
                                         src="https://res.cloudinary.com/dwfo16yhs/image/upload/v1719067021/img_prn231/zxgmfruitrszcrh5jvld.png"
                                         class="avatar" alt="Avatar">
                                </a>
                            </td>
                            <td>@item.UserName</td>
                            <td>@item.Email</td>
                            <td>@item.Role.RoleName</td>
                            @if (item.Status == true)
                            {
                                <td><span class="status text-success">&bull;</span> Active</td>
                            }
                            else
                            {
                                <td><span class="status text-danger">&bull;</span>Suspended</td>
                            }
                            <td>
                                <a asp-page="/Admin/ManageUserDetail" asp-route-id="@item.UserId" class="settings" title="View" data-toggle="tooltip">
                                    <i class="material-icons">&#xE8f4;</i>
                                </a>
                                @if (TempData["User"] == "Customer")
                                {
                                    @if (item.Status == true)
                                    {
                                        <a asp-page-handler="ChangeStatusUser" asp-route-id="@item.UserId" asp-route-check="Customer" class="unlock" title="Active" data-toggle="tooltip" onclick="return confirmLock('@item.UserId');">
                                            <i class="material-icons">&#xE898;</i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a asp-page-handler="ChangeStatusUser" asp-route-id="@item.UserId" asp-route-check="Customer" class="unlock" title="Suspended" data-toggle="tooltip" onclick="return confirmUnlock('@item.UserId');">
                                            <i style="color: red" class="material-icons">&#xE897;</i>
                                        </a>
                                    }
                                }
                                else
                                {
                                    @if (item.Status == true)
                                    {
                                        <a asp-page-handler="ChangeStatusUser" asp-route-id="@item.UserId" asp-route-check="Staff" class="unlock" title="Active" data-toggle="tooltip" onclick="return confirmLock('@item.UserId');">
                                            <i class="material-icons">&#xE898;</i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a asp-page-handler="ChangeStatusUser" asp-route-id="@item.UserId" asp-route-check="Staff" class="unlock" title="Suspended" data-toggle="tooltip" onclick="return confirmUnlock('@item.UserId');">
                                            <i style="color: red" class="material-icons">&#xE897;</i>
                                        </a>
                                    }
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @if (TempData["User"] == "Customer")
            {
                <div class="clearfix">
                    <div class="hint-text">Showing <b>@Model.Users.Count</b> out of <b>@Model.TotalItemsCustomer</b> entries</div>
                    <ul class="pagination">
                        <li class="page-item @(Model.PageIndex == 1 ? "disabled" : "")">
                            <a href="@Url.Page("/Admin/ManageUsers", new { pageIndex = 1 })" class="page-link">First</a>
                        </li>
                        <li class="page-item @(Model.PageIndex == 1 ? "disabled" : "")">
                            <a href="@Url.Page("/Admin/ManageUsers", new { pageIndex = Model.PageIndex - 1 })" class="page-link">Previous</a>
                        </li>
                        @for (int i = 1; i <= Math.Ceiling((double)Model.TotalItemsCustomer / Model.PageSize); i++)
                        {
                            <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                                <a href="@Url.Page("/Admin/ManageUsers", new { pageIndex = i })" class="page-link">@i</a>
                            </li>
                        }
                        <li class="page-item @(Model.PageIndex == Math.Ceiling((double)Model.TotalItemsCustomer / Model.PageSize) ? "disabled" : "")">
                            <a href="@Url.Page("/Admin/ManageUsers", new { pageIndex = Model.PageIndex + 1 })" class="page-link">Next</a>
                    </li>
                </ul>
                </div>
            }
            else
            {
                <div class="clearfix">
                    <div class="hint-text">Showing <b>@Model.Users.Count</b> out of <b>@Model.TotalItemsStaff</b> entries</div>
                    <ul class="pagination">
                        <li class="page-item @(Model.PageIndex == 1 ? "disabled" : "")">
                            <a href="@Url.Page("/Admin/ManageUsers", new { handler = "OnGetStaffAsync", pageIndex = 1 })" class="page-link">Đầu</a>
                        </li>
                        <li class="page-item @(Model.PageIndex == 1 ? "disabled" : "")">
                            <a href="@Url.Page("/Admin/ManageUsers", new {handler = "OnGetStaffAsync",  pageIndex = Model.PageIndex - 1 })" class="page-link">Trước</a>
                        </li>
                        @for (int i = 1; i <= Math.Ceiling((double)Model.TotalItemsStaff / Model.PageSize); i++)
                        {
                            <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                                <a href="@Url.Page("/Admin/ManageUsers", new {handler = "OnGetStaffAsync",  pageIndex = i })" class="page-link">@i</a>
                            </li>
                        }
                        <li class="page-item @(Model.PageIndex == Math.Ceiling((double)Model.TotalItemsStaff / Model.PageSize) ? "disabled" : "")">
                            <a href="@Url.Page("/Admin/ManageUsers", new {handler = "OnGetStaffAsync",  pageIndex = Model.PageIndex + 1 })" class="page-link">Tiếp</a>
                        </li>
                    </ul>
                </div>
            }
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<script type="text/javascript">
    function confirmLock(userId) {
        return confirm('Bạn có muốn khóa người dùng có id ' + userId + ' không?');
    }

    function confirmUnlock(userId) {
        return confirm('Bạn có muốn mở khóa người dùng có id ' + userId + ' không?');
    }
</script>